browser=chrome
headless=false
browser.width=1920
browser.height=1080

timeout.explicit=15
timeout.page=30
timeout.script=20
timeout.polling=200

innowise.url=https://innowise.com
localhost.url=http://localhost:8081

screenshots.enabled=true
screenshots.dir=target/screenshots

highlight.enabled=false
debug.mode=false